### ISSUE TITLE
support line break in cell

### ISSUE THREAD

**Issue by AuroraDysis** [haydenull/logseq-plugin-markdown-table#11]
**Describe the bug**
cell内无法换行

**Expected behavior**
使用shift+enter或enter应该创建一个新行

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 0.6.5

**Comment by haydenull** [comment]
主要是因为logseq不支持表格内换行，所以插件也没有支持

**Comment by AuroraDysis** [comment]
确实没有相关文档，尝试了一下可以使用hiccup换行
```md
|a|b|
|---|---|
|ddd|eee[:br]fff|
```

**Comment by haydenull** [comment]
感谢提示，我研究一下

**Comment by haydenull** [comment]
1.7.0 版本支持了单元格内换行，使用 `Shift + Enter`

**Comment by AuroraDysis** [comment]
非常感谢
