### ISSUE TITLE
Confirm button does not close the editor

### ISSUE THREAD

**Issue by Nightwindx** [haydenull/logseq-plugin-markdown-table#25]
Thank you for the plugin haydenull.
I would like to point out an issue with the "**Confirm**" button in the editor.
It saves the changes made to the table, however, to exit the editor I need to click cancel after I have already clicked confirm (which does not let me exit the editor)
To simplify: 
**Expected**: Confirm should save changes and close the editor
**Reality**: Confirm saves changes but does not close the editor

I am using the **0.9.19 Logseq version**

**Comment by larslue** [comment]
On top of this, pressing `Esc` should also be mapped to saving and closing the table editor.

**Comment by xiaoker** [comment]
me too
