### ISSUE TITLE
Self signed cert-related error during install  

### ISSUE THREAD

**Issue by YouShallNotCrash** [haydenull/logseq-plugin-markdown-table#28]
**Describe the bug**
While trying to install the plugin I receive a message:
`[Error]<logseq-markdown-table> :release-channel-issue "request to https://api.github.com/repos/haydenull/logseq-plugin-markdown-table/releases/latest failed, reason: self signed certificate in certificate chain"]`

**Expected behavior**
Succesful plugin installation upon pressing "Install" in Logseq Marketplace

**Screenshots**
<img width="1092" alt="Screenshot 2024-07-08 at 14 21 23" src="https://github.com/haydenull/logseq-plugin-markdown-table/assets/143208401/eadc612f-a91c-4ba1-ab00-a3330bfe1ab7">

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.5
 - Version:Logseq version 0.10.9

**Comment by haydenull** [comment]
This should be a network issue with the device. Please try again several times.

**Comment by YouShallNotCrash** [comment]
You are very right, that was most probably local network thing, which was blocking me.
Closing :)
