### ISSUE TITLE
paste from xlsx

### ISSUE THREAD

**Issue by cloudrflight** [haydenull/logseq-plugin-markdown-table#3]
can paste from xlsx data?
like:
columnA \t columnB
111         \t  2222

**Comment by haydenull** [comment]
Sorry, this plugin is used to assist in editing the markdown table, maybe a new plugin would be better for conversion xlsx data.

**Comment by haydenull** [comment]
this may help you. https://twitter.com/hkgnp/status/1499720222320001028
