### ISSUE TITLE
Getting console errors when trying to edit a md table.

### ISSUE THREAD

**Issue by jenningsb2** [haydenull/logseq-plugin-markdown-table#4]
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'references')

GIF of issue:
![Kapture 2021-12-04 at 10 36 25](https://user-images.githubusercontent.com/29644050/144715480-416e7f64-2acc-4ebc-9d9c-40bcfab1b13e.gif)

**Comment by haydenull** [comment]
The error is caused by parse [[]] failed, version 1.2.3 should have fixed it. If there is any problem, please open this issue again.
