### ISSUE TITLE
Faster access

### ISSUE THREAD

**Issue by Alejandro-Stolz** [haydenull/logseq-plugin-markdown-table#8]
Firstly I love the plugin, it makes my life easier. I was wondering if it would be possible by any means to have a shortcut or an easier way to enter the edit mode, without having to right click and select the option which is always one of the last ones

**Comment by haydenull** [comment]
This is a good idea. I added a new slash command 'markdown-table-editor' in version 1.6.0. I hope it can help you.

![2022-02-23 14 26 58](https://user-images.githubusercontent.com/17695989/155271461-da588391-5db9-4044-95b1-78b1616c8822.gif)
.
