### ISSUE TITLE
the plugin didnt work

### ISSUE THREAD

**Issue by liangjun-gong** [haydenull/logseq-plugin-markdown-table#9]
I couldn't use the plugin after installing it from a local file, or it didn't work. The screenshots are as follows:

![](https://gitee.com/gongliangjun/blog-images/raw/master/202203022244307.png)

![](https://gitee.com/gongliangjun/blog-images/raw/master/202203022244339.gif)

I want to know whether the plugin is deprecated. If not, how can I use it, thanks!

**Comment by haydenull** [comment]
If you are installing it for the first time, you can try restarting logseq

**Comment by liangjun-gong** [comment]
I reinstalled the plugin and restarted logseq but it still didn't work.

**Comment by haydenull** [comment]
This question is a bit strange, what is your system and logseq version？

**Comment by liangjun-gong** [comment]
computer system: windows 10
logseq version: 0.6.1
I tried the slash command markdown-table-editor, but it didn't work.
In addition, I also reboot the computer but the problem is still unresolved. 
![](https://gitee.com/gongliangjun/blog-images/raw/master/202203041149806.gif)

**Comment by haydenull** [comment]
You can close and then enable the plug-in, and see if there has any error in the console. Use `ctrl+shift+i` in windows to open the devtool.
![2022-03-04 12 41 33](https://user-images.githubusercontent.com/17695989/156701065-53c46b82-b3dd-4a74-a1c1-a71d3d44039c.gif)

**Comment by liangjun-gong** [comment]
As the gif shows, nothing is displayed in the console.
By the way, I installed the markdown-table-editor plugin by loading unpacked plugin.

![](https://gitee.com/gongliangjun/blog-images/raw/master/202203041319117.gif)

**Comment by haydenull** [comment]
It looks like the plugin's code is not executed. So can you see if these files are in the package?

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/17695989/156707770-bdbcb384-22d2-484a-a445-dcf4c89885fb.png">
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/17695989/156707941-28f55cef-8b74-480e-ae5d-6c9967befde3.png">

**Comment by liangjun-gong** [comment]
the files in the package are shown below:
yes, my package was downloaded from [github release](https://github.com/haydenull/logseq-plugin-markdown-table/releases)？
![](https://gitee.com/gongliangjun/blog-images/raw/master/202203041405335.gif)

**Comment by haydenull** [comment]
May I ask how do you load this plugin, I tried `load unpacked plugin` with windows, the plugin will display the `Unpacked` logo, and there is a reload button.
I guess the problem is related to the plugin path, my current plugin path is `Users/xxxx/Downloads`.

![image](https://user-images.githubusercontent.com/17695989/156711692-9378e518-a3d4-4551-9753-d07f94b60a9b.png)

**Comment by liangjun-gong** [comment]
I downloaded the plugin package and put it in the logseq installation path(C:\Users\xxx(my computer username)\.logseq\plugins), then unzipped it. After that, I turned back to the logseq `plugin` and installed by `load unpacked plugin`, as shown in the following gif:

![](https://gitee.com/gongliangjun/blog-images/raw/master/202203041539695.gif)

**Comment by liangjun-gong** [comment]
![](https://gitee.com/gongliangjun/blog-images/raw/master/202203041549887.gif)

**Comment by haydenull** [comment]
I just reproduced the problem. The reason seems to be that the developer mode is turned off after loading the unpacked plugin, and then whether the mode is turned on or off, the plugin is considered to be downloaded from the marketplace.

The easiest solution is to uninstall the plugin and download it from the marketplace. Or move the plugin out of the `.logseq` folder and reinstall it.

**Comment by liangjun-gong** [comment]
I tried several times to install the plugin from the marketplace, but it all failed.
by the way, I used VPN

![](https://gitee.com/gongliangjun/blog-images/raw/master/202203041634894.png)

**Comment by haydenull** [comment]
There is nothing I can do about the network problem, you can try to put the plugin file in the Downloads (just not .logseq) folder, and then load the plugin again.

**Comment by liangjun-gong** [comment]
I turned off VPN and the result is the same.
In addition, I tested it on another computer(system: windows10) and there were failures when the plugin was installed from the marketplace. After the plugin was installed by `load unpacked plugin`, it still didn't work.

**Comment by liangjun-gong** [comment]
I'll try it, thanks for your help!

**Comment by haydenull** [comment]
You are welcome. The point is to let logseq recognize that the plugin is a load unpacked plugin, this state is marked with unpacked and the reload button.

**Comment by liangjun-gong** [comment]
As you suggested, the plugin can work now on my computer. Thanks again!

![](https://gitee.com/gongliangjun/blog-images/raw/master/202203051133077.gif)
